server:
  port: 8080

spring:
  application:
    name: wechat-server-java

wx:
  mp:
    appId: xxxxxxxxxx
    secret: xxxxxxxxxx
    token: xxxxxxxxxx
    aesKey: xxxxxxxxxx
    api-host: https://api.weixin.qq.com
    open-host: https://open.weixin.qq.com
    mp-host: https://mp.weixin.qq.com
api:
  token: xxxxxxxxxx
  send-code-keyword: 验证码
  code-template: "您正在登录 FanStars API, 验证码是: ${code}"
  code-length: 6
  code-expire-time: 300000
  width: 300
  height: 300
  margin: 1
  qrcode-scene-id: 1008
  qrcode-expire-time: 600
  custom-reply-map:
    lol: "英雄联盟"
    cf: "窜越火线"
    dnf: "地下城与勇士"

log:
  path: logs
